### ISSUE TITLE
Explore desirability and feasibility of Oauth2 support to shut Google 2-factor up.

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/FossaMail#14]
Just what it says on the tin.. Should be found in comm-esr38.

https://bugzilla.mozilla.org/show_bug.cgi?id=849540

**Comment by wolfbeast** [comment]
... We looked at this before, remember? At the time we were against it because it's plugging web technologies into non-web protocols/clients.

But if you want to tackle this and think it's a good thing to have regardless, then I'll defer to you.

**Comment by mattatobin** [comment]
You are likely right.. However, I want to put some research into looking if we can really do it.. Right now though is the hardcoding of set of google API keys that Thunderbird may just kill this again. I have to figure out if these are keys we can get for our selves.

Anyway, it doesn't hurt to bring it back up and take a poke at it.. Especially since users keep asking about it. Don't want to give the impression they are being ignored or anything.

**Comment by wolfbeast** [comment]
If it's tied in with Google API keys, then we can't do it as they are business-rate per volume of requests.
I'm not going to _pay_ Google to allow _them_ to force _their_ preferred auth method. That's topsy-turvy.

**Comment by wolfbeast** [comment]
gmail auth in v27 will be done using web-based oauth, so we should be all good. closing.
