### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by fermuch** [MoonchildProductions/FossaMail#17]
Hello. First I want to thank all of you for making FossaMail.

It's clear that Mozilla is [abandoning Thunderbird](https://www.yahoo.com/tech/mozilla-updates-firefox-more-less-abandons-thunderbird-firefox-181521744.html), and I'm trying to find a suitable home to move. So, the question is: what will happen to FossaMail once Thunderbird is fully closed?

**Comment by wolfbeast** [comment]
FossaMail is not associated with Mozilla or Thunderbird. There is no link to Thunderbird's development (or abandonment) and no reason for FossaMail to have anything "happen to it" because of Mozilla's plans.
