### ISSUE TITLE
Update or update notifcation

### ISSUE THREAD

**Issue by MartinX3** [MoonchildProductions/FossaMail#23]
I miss the ability to update the application or to get informed about an updated version.

High security relevance!

**Comment by wolfbeast** [comment]
Subscribe to the RSS feed (you can do this inside FossaMail) of the FossaMail announcements.

So far the administrative overhead for setting up automatic updating has not been worth itfor the relatively low number of users.
If you feel like setting up, maintaining and paying for an automatic updates server and doing the necessary release engineering for it, then I'll be more than happy to pass that torch to you (and supply you with mar files for it).

**Comment by MartinX3** [comment]
Thank you, I will search the option.
Btw. i clicked on the Menu HELP -> Whats New / Release Notes and there is a blank site / HTTP not found error
