### ISSUE TITLE
Addons for Thunderbird 38 not compatible

### ISSUE THREAD

**Issue by MartinX3** [MoonchildProductions/FossaMail#25]
> Hoisted most of the application code to be Thunderbird 38 equivalent in functionality.

I thought, i would now be able to update my addons to the versions which are build for TB 38.

As example.
Thunderbird-Conversations 2.7 stopped working after ugrading from 25 to 27.
The Version 2.10.2 build is the last one for v38.

And i need the coversation view
(Watching the email conversation like in a messenger, seeing what i wrote and what the other wrote, etc.)

Edit:
I manually changed the install.rdf of every v38 compatible addon update.
Now everything is working fine.
But of course the auto update is now out of order, since the v27 upgrade.
There should be a compatiblity warning when i want to update these TB addons, instead to deny it.

**Comment by wolfbeast** [comment]
You'll have to edit the install.rdf of the extension to indicate the version range to include FossaMail's application version.

**Comment by wolfbeast** [comment]
I guess it's something to consider to just re-number FossaMail to the FE compatversion instead of the BE platform version... @mattatobin what do you think?

**Comment by MartinX3** [comment]
Or putting an alias inside the application reflecting the current code base of the thunderbird version, you're compatible with.

But why you did change the versions numbner?

And on the next rebase, will the version number make a big jump and irritate users?

**Comment by wolfbeast** [comment]
... Version numbers have always been in line with the version of Pale Moon FossaMail is built on.

There won't be a "next re-base" either. Not sure where you get that idea from.

**Comment by MartinX3** [comment]
Yes, i know this fact, but i missunderstood you, if i read your answer again.
I'm sorry. I thought, you want to push FossaMail to Version 38. xD

What do you mean with re-number it to the  FE compatversion instead of the BE platform version?

**Comment by wolfbeast** [comment]
> I thought, you want to push FossaMail to Version 38. xD

That's exactly what I'm pondering. Re-number the application to the front-end compatibility version of Thunderbird for the sake of extensions, instead of keeping the back-end versioning for the platform it builds on. The other option would be to make an elaborate dual-GUID setup like the browser has which, although possible, isn't worth the investment, I think.

**Comment by MartinX3** [comment]
That would mean, i see version 38 in the about dialogue and when you
"Hoisted most of the application code to be Thunderbird 94 equivalent in functionality."
then, you will push FossaMail to version 94?

This hard version jumps would irritate an user, who don't know why, i think

**Comment by wolfbeast** [comment]
You c;learly haven't been paying attention to what I said about re-basing.

**Comment by mattatobin** [comment]
@wolfbeast Just make a small ifdef'd edit in XPIProvider and friends to accept Thunderbird's applicationVersion.

Of course, I think FossaMail should get the treatment Pale Moon has been getting going forward. Dual-GUID, AUS (both add-ons and application).

But what do I know.

**Comment by mattatobin** [comment]
As per the simplest fix.. Of course this will not count comparisons in chrome.manifest but there are so few extensions anyway when people ask they can told what to do but i'd say this would cover 99% of Thunderbird extensions.

Adjusting tabspaces of course:

@ http://xref.palemoon.org/palemoon-trunk/source/toolkit/mozapps/extensions/internal/XPIProvider.jsm#129

> #ifdef MOZ_PHOENIX_EXTENSIONS
>  const FIREFOX_ID                      = "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}"
>  const FIREFOX_APPCOMPATVERSION        = "27.9"
> #elif MOZ_THUNDERBIRD
>  const THUNDERBIRD_APPCOMPATVERSION        = "38.9"
> #endif

@ http://xref.palemoon.org/palemoon-trunk/source/toolkit/mozapps/extensions/internal/XPIProvider.jsm#6412

> #ifdef MOZ_THUNDERBIRD
>      if (app.id == Services.appinfo.ID) {
>        version = THUNDERBIRD_APPCOMPATVERSION;
> #else
>      if (app.id == Services.appinfo.ID) {
>        version = aAppVersion;
> #endif

@ depending on if it gets picked up down that level or not add this to the end of http://xref.palemoon.org/palemoon-trunk/source/toolkit/mozapps/extensions/internal/moz.build

>  if CONFIG['MOZ_THUNDERBIRD']:
>      DEFINES['MOZ_THUNDERBIRD'] = 1

**Comment by wolfbeast** [comment]
I'm choosing to simply update the version number of the application to 38. _That_ is the simplest, most straight-forward fix with the highest degree of logic to it.

Ultimately it doesn't matter what back-end FossaMail builds on (which is exactly why I've been wanting to keep our repos for this separate) and looking at it from an application point of view, the application code is simply "mostly" Thunderbird 38. Our FossaMail application version should reflect that for the sake of AUS, extensions, simplified maintenance, and giving the correct message to other developers who may want to inspect/use our code, with a minimum of complexity in the code. It will also avoid discrepancies with extensions checking appVersion in their scripting and in general avoids version mismatch headaches in different parts of the application.

Our resulting binary will be FossaMail 38.0 -> built on the Pale Moon 27 back-end (but that appversion won't be part of a different XUL application like FossaMail) -> built on Goanna 3.

**Comment by wolfbeast** [comment]
Resolved by d684874a020561fab249ec3ef9cd10ac5da44ba0
