### ISSUE TITLE
Folder Pane doesn't conform to dark OS theme

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/FossaMail#9]
https://forum.palemoon.org/viewtopic.php?f=34&t=10418

Thunderbird 22 introduced a new "grain" overlay for the folder pane ([bug #845819] (https://bugzilla.mozilla.org/show_bug.cgi?id=845819)) that is used regardless of OS theme. As a result, the folder pane does not conform to dark OS themes. This was negatively received by a number of users with dark themes, and was eventually changed (in TB 28 I believe). Although they promised to, Mozilla never back ported a patch to 24ESR (and their solution in v28 depended on much refactoring, etc. and broke v24 if applied as-is).

Likely the easiest solution would be to simply revert the change introduced by TB 22 and remove the "grainy" background (which would allow the folder pane color to be determined by the OS theme in use).

**Comment by trav90** [comment]
Moonchild, feel free to assign myself to this.

**Comment by wolfbeast** [comment]
Yeah sounds like a plan to just undo the TB22 change.
Feel free to take it.

**Comment by wolfbeast** [comment]
Assuming this is resolved, I don't expect any issues from this.
Since you removed the grain image: are you sure it's not used elsewhere?

**Comment by trav90** [comment]
It was also used by the chat component. PR #11 should remove uses of grain.png completely.

**Comment by wolfbeast** [comment]
Thanks! Merged that one as well to complete this.
